matrix:
  include:
    - os: linux
      jdk: oraclejdk8
      sudo: false
      addons:
        apt:
          # Flutter depends on /usr/lib/x86_64-linux-gnu/libstdc++.so.6 version GLIBCXX_3.4.18
          sources:
            - ubuntu-toolchain-r-test # if we don't specify this, the libstdc++6 we get is the wrong version
            - llvm-toolchain-precise # for clang-format-5.0
          packages:
            - lib32stdc++6 # https://github.com/flutter/flutter/issues/6207
            - libstdc++6
            - fonts-droid
            - clang-format-5.0
      before_script:
        - ./script/before_build_apks.sh
        - export ANDROID_HOME=`pwd`/android-sdk
        - git clone https://github.com/flutter/flutter.git
        - export PATH=`pwd`/flutter/bin:`pwd`/flutter/bin/cache/dart-sdk/bin:$PATH
        - flutter doctor
        - pub global activate flutter_plugin_tools
      script:
        - flutter build apk
    - os: osx
      language: generic
      osx_image: xcode9.3
      before_script:
        - ./script/before_build_ipas.sh
        - git clone https://github.com/flutter/flutter.git
        - export PATH=`pwd`/flutter/bin:`pwd`/flutter/bin/cache/dart-sdk/bin:$PATH
        - flutter doctor
        - pub global activate flutter_plugin_tools
      script:
        - flutter build ios
  allow_failures:
  - os: osx
  fast_finish: true
cache:
  directories:
    - $HOME/.pub-cache
